### ISSUE TITLE
Alguma Integração para o WordPress?

### ISSUE THREAD

**Issue by monecchi** [mundipagg/Magento.Integracao#10]
Existe um plano de lançamento para integração com o WordPress, existe algum plugin por outros desenvolvedores que funcione com a Mundipagg?

**Comment by felipebool** [comment]
Olá, monecchi. Tudo bom?

Existe uma integração feita pela comunidade aqui neste link https://wordpress.org/plugins/woocommerce-mundipagg/ (nós não oferecemos suporte).

Estamos trabalhando atualmente em uma integração in-house para o Woocommerce, em breve iremos disponibilizar uma versão. Qual a sua necessidade? Se quiser esperar, já, já teremos a versão oficial. :)

Até.
