### ISSUE TITLE
Magento 2

### ISSUE THREAD

**Issue by thiagosantos** [mundipagg/Magento.Integracao#23]
Há alguma previsão para liberarem ou iniciarem o desenvolvimento de uma versão oficial da Mundipagg para o Magento 2?

**Comment by ThiagoBarradas** [comment]
Olá @thiagosantos !
Estamos em fase de desenvolvimento do Magento 2, em breve disponibilizaremos no marketplace do Magento e no GitHub, continue acompanhando que divulgaremos por nossos principais meios de comunicação, inclusive aqui no repositório da versão do Magento 1.

**Comment by aandrade1234** [comment]
@ThiagoBarradas  vc tem um horizonte (1, 2 3 meses), pois estou desenvolvendo um módulo para M2, se for logo vou parar para focar em outras tarefas.
