### ISSUE TITLE
Problema na versão v2.12.08

### ISSUE THREAD

**Issue by michellcampos** [mundipagg/Magento.Integracao#47]
Depois que fiz o update para a versão v2.12.08 não consegui mais fechar pedido.
Quando escolho um método de pagamento e avanço aparece um alert com uma mensagem.

A versão v2.12.07 está mais estável.

Flw

**Comment by vitormattos** [comment]
Olá @michellcampos 

Pode nos dar mais evidências do que ocorreu?

Consegue disponibilizar um print do alert que recebeu?

Pode disponibilizar os arquivos `exception.log` e `system.log`? Dica: faz um backup dos teus logs, faça o passo a passo para atualização e ao exibir o alert informado, faça uma cópia do exception e system logs para anexar a esta issue. Estes arquivos ficam na pasta `var/log/` na raiz do Magento

**Comment by michellcampos** [comment]
Olá @vitormattos 

Seguem dois prints com o erro.
![screenshot from 2017-09-20 15-13-48](https://user-images.githubusercontent.com/1236173/30660211-7f68da18-9e16-11e7-91dc-197d3d32c4bc.png)
![screenshot from 2017-09-20 15-13-34](https://user-images.githubusercontent.com/1236173/30660212-7f69946c-9e16-11e7-962f-b10e9a322d99.png)

Caso seja algum erro de configuração, poderia me orientar?

Obrigado

**Comment by michellcampos** [comment]
@vitormattos 

Segue o print do var/log/exception.log

![screenshot from 2017-09-20 15-21-14](https://user-images.githubusercontent.com/1236173/30660517-76271248-9e17-11e7-808a-f47c44f41661.png)

**Comment by michellcampos** [comment]
@vitormattos 

Pelo que vi aqui... realmente a variável $interest não foi setada.

![screenshot from 2017-09-20 15-24-57](https://user-images.githubusercontent.com/1236173/30660666-026ad46a-9e18-11e7-85fd-c2ae74ba83f7.png)


Que valor deveria vir nela?

**Comment by vitormattos** [comment]
Já estamos subindo uma nova versão corrigindo isto.

**Comment by michellcampos** [comment]
Ok. Obrigado.

**Comment by felipebool** [comment]
Oi, @michellcampos. Poderia validar a solução?
Obrigado.

https://github.com/mundipagg/Magento.Integracao/releases/tag/v2.12.09

**Comment by michellcampos** [comment]
Funcionando! ;-)

Obrigado @felipebool

**Comment by felipebool** [comment]
Show!
