### ISSUE TITLE
Status de Retorno

### ISSUE THREAD

**Issue by satodu** [mundipagg/Magento.Integracao#58]
Bom dia,

Alguém sabe me dizer qual é o status que ele a mundiPagg retorna para o pedido no magento ?

Obrigado,

att,

Eduardo Sato

**Comment by satodu** [comment]
Volta como "Processando".

**Comment by michelpl** [comment]
Olá @satodu.
Isso mesmo, para pedidos pagos o status padrão é "Processando".
