### ISSUE TITLE
 Classe 'Uecommerce_Mundipagg_Model_Resource_Setup' nao encontrada

### ISSUE THREAD

**Issue by crfwilliams** [mundipagg/Magento.Integracao#59]
Fiz a instalação manual do plugin e ao executar a minha aplicação magento ocorre o segiunte erro.

Fatal error: Class 'Uecommerce_Mundipagg_Model_Resource_Setup' not found in /opt/lampp/htdocs/magento/includes/src/Mage_Core_Model_Resource_Setup.php on line 234

Estou usando a versão 1.9.3 do magento.

**Comment by felipebool** [comment]
Olá, como você fez a instalação manual, pode ter acontecido algum problema com as permissões. Consegue chegar se está tudo com as permissões corretas?

**Comment by crfwilliams** [comment]
Era exatamente isso,
Permissão nas pastas.

Muito obrigado!

**Comment by crfwilliams** [comment]
Boar tarde,

Analisei e todas as pastas estão com permissão de leitura e escrita.

**Comment by crfwilliams** [comment]
Finalmente consegui resolver.

O problema era porque o compile (System>tools>compilation) estava habilitado.

Obrigado!
