### ISSUE TITLE
Módulo desatualizado em relação à Magento Connect

### ISSUE THREAD

**Issue by thiagobs** [mundipagg/Magento.Integracao#7]
Seria muito bom se o módulo estivesse atualizado aqui, pois na versão do Magento Connect a versão do módulo já está em 2.9.18.

**Comment by michelpl** [comment]
Olá Thiago. Obrigado pela sua contribuição.
Em breve realizaremos atualizações no módulo e com isso acertaremos essa diferença.

**Comment by michelpl** [comment]
Uma nova versão foi lançada e com isso equiparamos Magento Connect com Github.
