### ISSUE TITLE
Observer sessionUpdate

### ISSUE THREAD

**Issue by deogenessignativa** [mundipagg/Magento.Integracao#9]
Olá,

Falo em nome da empresa [Signativa](https://www.signashop.com.br/) um ecommerce baseado em Magento, atualmente temos uma fatia de clientes que utilizam seu gateway para efetuar seus pagamentos.

Encontramos em nossos ambientes de homologação um problema que ocorre por conta da ação na classe: _**Uecommerce_Mundipagg_Model_Observer::sessionUpdate($observer)**_ este método parece eliminar duas flags **"approval_request_success"** e **"authorized_amount"** quando a action não é vinda do _**"mundipagg_standard"**_

O problema acontece quando este observer acaba observando módulos como o [Panalysis TagManager ](https://www.magentocommerce.com/magento-connect/google-tag-manager-plus-1.html) na hora do finalizar compra.

Ao finalizar uma compra existe o redirecionamento em **_Uecommerce_Mundipagg_Model_Standard::getOrderPlaceRedirectUrl_** para o método **_Uecommerce_Mundipagg_StandardController::successAction_** (em caso de sucesso) e ai é onde o Tag Manager é acionado fazendo com que o observer limpe a flag **"approval_request_success"** antes de ser utilizada no successAction, causando erro por chegar nula.

Este problema foi encontrado para o módulo Tag Manager mas pode acontecer para qualquer módulo que o cliente queira inserir para personalizar seu e-commerce, o problema está em observar o controller_action_predispatch, portanto acredito ser interesse de vocês também.

Pedimos sua ajuda para entender porque é tão necessário limpar esta flag e o que aconteceria caso não fosse limpa, assim podemos tomar procedimentos para ajustes internos até que sua equipe possa analisar a situação e realizar um ajuste oficial.

Desde já agradecemos.

**Comment by michelpl** [comment]
Olá Signativa.
Vimos que você também enviou um chamado para o nosso suporte. Sugerimos que você sempre abra o chamado por lá pois lá mantemos o registro e o SLA de resposta do time é menor.
Estamos avaliando o caso e te daremos uma resposta por e-mail.

Abraços,
